# fly.toml app configuration file generated for all-payments-api on 2025-05-14T01:36:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'all-payments-api'
primary_region = 'jnb'

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
